title: Blog de Toam
url: "http://thomas.brelet.net"
baseurl: ""
twitter_username: toam
github_username:  toam
permalink: /:day-:month-:year-:title
citation_category_name: "quote"

exclude: ["archive"]

# Build settings
markdown: kramdown
highlighter: pygments
